main = "src/index.js"
name = "hotstack-worker"
compatibility_date = "2024-11-01"

account_id = "ad41fcfe1a84b27c62cc5cc9d590720e"

[[r2_buckets]]
binding = "HOTSTACK_BUCKET"
bucket_name = "hotstack-intake-bucket"

[site]
bucket = "./public"
include = ["*"]
